name: Node CI

on:
  push:
    branches:
    - master
    - release/*

  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install packages and test
      run: |
        yarn
        yarn lint
        yarn test
