name: Node CI

on: 
  push:
    branches:
    - master
    - release/*

  pull_request:
    branches:
    - master

jobs:
  checkout:
    runs-on: ubuntu-latest
    container: 
      image: node:latest
      env:
        NODE_ENV: development
      volumes:
        - node_modules:/__w/next-typescript-template/next-typescript-template

 
    steps:
    - uses: actions/checkout@v1
    - name: Install packages
      run: |
        touch test.txt
        pwd
        ls -la

  lint:
    needs: checkout
    runs-on: ubuntu-latest
    container: 
      image: node:latest
      env:
        NODE_ENV: development
      volumes:
        - node_modules:/__w/next-typescript-template/next-typescript-template
    steps:
    - name: Test
      run: |
        pwd
        ls -la
